version: '3'

services:
  ai:
    container_name: ai_choreography
    build:
      context: .
      dockerfile: ai/Dockerfile
    ports:
      - "8001:8001"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
  crm:
    container_name: crm_choreography
    build:
      context: .
      dockerfile: crm/Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - redis_crm_choreography
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
  redis_crm_choreography:
    container_name: redis_crm_choreography
    image: "redis:alpine"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
  doors:
    container_name: doors_choreography
    build:
      context: .
      dockerfile: doors/Dockerfile
    ports:
      - "8003:8003"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
  ereceipt:
    container_name: ereceipt_choreography
    build:
      context: .
      dockerfile: ereceipt/Dockerfile
    ports:
      - "8004:8004"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
  messages:
    container_name: messages_choreography
    build:
      context: .
      dockerfile: messages/Dockerfile
    ports:
      - "8005:8005"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
  payments:
    container_name: payments_choreography
    build:
      context: .
      dockerfile: payments/Dockerfile
    ports:
      - "8006:8006"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
  pim:
    container_name: pim_choreography
    build:
      context: .
      dockerfile: pim/Dockerfile
    ports:
      - "8007:8007"
    depends_on:
      - redis_pim_choreography
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
  redis_pim_choreography:
    container_name: redis_pim_choreography
    image: "redis:alpine"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
  receipt:
    container_name: receipt_choreography
    build:
      context: .
      dockerfile: receipt/Dockerfile
    ports:
      - "8008:8008"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
  screen:
    container_name: screen_choreography
    build:
      context: .
      dockerfile: screen/Dockerfile
    ports:
      - "8009:8009"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
  terminal:
    container_name: terminal_choreography
    build:
      context: .
      dockerfile: terminal/Dockerfile
    ports:
      - "8010:8010"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
